image:
  - Visual Studio 2017
  - Ubuntu
init:
  - git config --global core.autocrlf input
install:
  - chmod +x build.sh
build_script:
  - cmd: build.cmd
  - sh: ./build.sh
test: off
version: 0.0.1.{build}
artifacts:
  - path: 'dist\*.nupkg'
    name: NuGet

  - path: docs\coverage
    name: TestCoverage
