image:  
  - Visual Studio 2017
  - Ubuntu
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
  - sh: ./build.sh
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
